config/routes.rb
Rails.application.routes.draw do
  root 'events#index'
  get '/login', to: 'sessions#new', as: 'new_login'
  post '/login', to: 'sessions#create', as: 'create_login'
  delete '/logout', to: 'sessions#destroy', as: 'logout'
  resources :users, only: [:new, :create, :show]
  resources :events, only: [:index, :new, :create, :show]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
    scope :previous, -> { where("date < ?", Date.today) }
    scope :upcoming, -> { where("date >= ?", Date.today) }
    belongs_to :creator, class_name: 'User'
    has_many :invitations
    has_many :attendees, through: :invitations
end

app/models/invitation.rb
class Invitation < ApplicationRecord
    belongs_to :event
    belongs_to :attendee, class_name: 'User'
end

app/models/user.rb
class User < ApplicationRecord
  has_many :events, foreign_key: 'creator_id'
  has_many :invitations, foreign_key: 'attendee_id'
  has_many :attended_events, through: :invitations, source: :event, class_name: 'Event'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events = Event.all
  end

  def new
    @event = Event.new
  end

  def create
    current_user.events.create(event_params)
  end

  def show
    @event = Event.find(params[:id])
  end

  private

  def event_params
    params.require(:event).permit(:title, :description, :date)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(username: params[:login][:username])
    if user
      log_in(user)
      redirect_to root_url
    else
      flash.now[:warning] = 'Incorrect username'
      render 'new'      
    end
  end

  def destroy
    log_out
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    User.create(user_params)
  end

  def show
    @user = User.find(params[:id])
  end

  private

  def user_params
    params.require(:user).permit(:username)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

  def current_user?(user)
    user == current_user
  end
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/events/_events.html.erb
<section class="section">
  <h3 class="title is-size-4">Upcoming events</h3>
  <div class="container columns">
    <% Event.upcoming.each do |e| %>
      <div class="box column is-one-quarter">
        <h4><%= link_to e.title, event_url(e.id) %></h4>
      </div>
    <% end %>
  </div>

  <h3 class="title is-size-4">Previous events</h3>
  <div class="container columns">
    <% Event.previous.each do |e| %>
      <div class="box column is-one-quarter">
        <h4><%= link_to e.title, event_url(e.id) %></h4>
      </div>
    <% end %>
  </div>
</section>

app/views/events/index.html.erb
<section class="section">
  <div class="container">
    <h1 class="title">Events</h1>
    <%= render "events/events" %>
  </div>
</section>

app/views/events/new.html.erb
<section class="section">
  <div class="container">
    <div class="box">
      <%= simple_form_for @event do |f| %>
        <div class="field">
          <div class="control">
            <%= f.input :title, wrapper: false, input_html: { class: "input" },
                                label_html: { class: "label" } %>
          </div>
        </div>
        <div class="field">
          <div class="control">
            <%= f.input :description, wrapper: false, input_html: { class: "textarea" },
                                         label_html: { class: "label" } %>
          </div>
        </div>
        <div class="field">
          <div class="control">
            <%= f.input :location, wrapper: false, input_html: { class: "input" }, 
                                   label_html: { class: "label" } %>
          </div>
        </div>
        <div class="field">
          <div class="control">
            <%= f.input :date, as: :date, html5: true, wrapper: false, input_html: { class: "date" },
                              label_html: { class: "label" } %>
          </div>
        </div>
      
        <%= f.button :submit, class: "button"%>
      <% end %>

    </div>
  </div>
</section>
      

app/views/events/show.html.erb
<section class="section">
  <div class="columns container">
    <div class="column panel is-one-fifth is-offset-1">
      <p class="panel-heading">Attendees</p>
      <% @event.attendees.each do |a| %>
        <%= link_to a.username, user_url(a.id), class: "panel-block" %>
      <% end %>
    </div>
    <div class="column box is-three-fifths">
      <h1 class="title"><%= @event.title %></h1>
      <h2 class="subtitle">Creator: <%= @event.creator.username %></h2>
      <p><%= @event.description %></p>
      <span>Date: <%= @event.date %></span>
    </div>
  </div>
</section>

app/views/layouts/_navbar.html.erb
<nav class="navbar" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <%= link_to "Private Events", root_url, class: "navbar-item is-size-4"%>

    <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>

  <div id="navbarBasicExample" class="navbar-menu">
    

    <div class="navbar-end">
      <% if logged_in? %>
        <div class="navbar-item">
          <%= link_to "Create an event", new_event_path, class: "navbar-item button is-dark" %>
        </div>
        <div class="navbar-item has-dropdown is-hoverable">
          <%= link_to current_user.username, "#", class: "navbar-link" %>
          <div class="navbar-dropdown">
            <%= link_to "My profile", user_url(current_user.id), class: "navbar-item" %>
            <%= link_to "Logout", logout_url, method: :delete, class: "navbar-item" %>
          </div>
        </div>
      <% else %>
        <div class="navbar-item">
          <div class="buttons">
            <%= link_to "Sign up", new_user_path, class: "button is-dark" %>
            <%= link_to "Log in", new_login_url, class: "button is-light" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/navbar" %>
    <%= yield %>
  </body>
</html>

app/views/shared/_login_form.html.erb
<%= simple_form_for :login do | f |%>
  <div class="field">
    <div class="control">
      <%= f.input :username,
                  input_html: { class: 'input' },
                  label: 'Username',
                  label_html: { class: 'label' },
                  wrapper: false, autofocus: true %>
    </div>
  </div>
  <%= f.submit "Login", class: 'button' %>
<% end %>

app/views/shared/_signup_form.html.erb
<%= simple_form_for @user do | f |%>
  <div class="field">
    <div class="control">
      <%= f.input :username,
                  input_html: { class: 'input' },
                  label: 'Username',
                  label_html: { class: 'label' },
                  wrapper: false, autofocus: true %>
    </div>
  </div>
  <%= f.button :submit, class: 'button' %>
<% end %>

app/views/users/_created_events.html.erb
<section class="section">
  <h3 class="title is-size-4">Upcoming events</h3>
  <div class="container columns">
    <% @user.events.upcoming.each do |e| %>
      <div class="box column is-one-quarter">
        <h4><%= link_to e.title, event_url(e.id) %></h4>
      </div>
    <% end %>
  </div>

  <h3 class="title is-size-4">Previous events</h3>
  <div class="container columns">
    <% @user.events.previous.each do |e| %>
      <div class="box column is-one-quarter">
        <h4><%= link_to e.title, event_url(e.id) %></h4>
      </div>
    <% end %>
  </div>
</section>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<section class="section">
  <div class="container">
    <h1 class="title">Create User</h1>
    <div class="box">
      <%= simple_form_for @user do | f |%>
        <div class="field">
          <div class="control">
            <%= f.input :username,
                        input_html: { class: 'input' },
                        label: 'Username',
                        label_html: { class: 'label' },
                        wrapper: false, autofocus: true %>
          </div>
        </div>
        <%= f.button :submit, class: 'button' %>
      <% end %>
    </div>
  </div>
</section>
  

app/views/users/show.html.erb
<section class="section">
  <div class="container">
    <h1 class="title">Your events</h1>
    <div class="container">
      <%= render "users/created_events" %>
    </div>
  </div>
</section>